/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeowstermindIndexRouteImport } from './routes/meowstermind/index'
import { Route as MeowstermindPlayRouteImport } from './routes/meowstermind/play'
import { Route as MonopawlyIndexRouteImport } from './routes/monopawly/index'
import { Route as MonopawlyCodeRouteImport } from './routes/monopawly/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeowstermindIndexRoute = MeowstermindIndexRouteImport.update({
  id: '/meowstermind/',
  path: '/meowstermind/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeowstermindPlayRoute = MeowstermindPlayRouteImport.update({
  id: '/meowstermind/play',
  path: '/meowstermind/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MonopawlyIndexRoute = MonopawlyIndexRouteImport.update({
  id: '/monopawly/',
  path: '/monopawly/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonopawlyCodeRoute = MonopawlyCodeRouteImport.update({
  id: '/monopawly/$code',
  path: '/monopawly/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/monopawly/$code': typeof MonopawlyCodeRoute
  '/meowstermind/': typeof MeowstermindIndexRoute
  '/monopawly/': typeof MonopawlyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/monopawly/$code': typeof MonopawlyCodeRoute
  '/meowstermind': typeof MeowstermindIndexRoute
  '/monopawly': typeof MonopawlyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/monopawly/$code': typeof MonopawlyCodeRoute
  '/meowstermind/': typeof MeowstermindIndexRoute
  '/monopawly/': typeof MonopawlyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meowstermind/play'
    | '/monopawly/$code'
    | '/meowstermind/'
    | '/monopawly/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meowstermind/play'
    | '/monopawly/$code'
    | '/meowstermind'
    | '/monopawly'
  id:
    | '__root__'
    | '/'
    | '/meowstermind/play'
    | '/monopawly/$code'
    | '/meowstermind/'
    | '/monopawly/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeowstermindPlayRoute: typeof MeowstermindPlayRoute
  MonopawlyCodeRoute: typeof MonopawlyCodeRoute
  MeowstermindIndexRoute: typeof MeowstermindIndexRoute
  MonopawlyIndexRoute: typeof MonopawlyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meowstermind/': {
      id: '/meowstermind/'
      path: '/meowstermind'
      fullPath: '/meowstermind/'
      preLoaderRoute: typeof MeowstermindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meowstermind/play': {
      id: '/meowstermind/play'
      path: '/meowstermind/play'
      fullPath: '/meowstermind/play'
      preLoaderRoute: typeof MeowstermindPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monopawly/': {
      id: '/monopawly/'
      path: '/monopawly'
      fullPath: '/monopawly/'
      preLoaderRoute: typeof MonopawlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monopawly/$code': {
      id: '/monopawly/$code'
      path: '/monopawly/$code'
      fullPath: '/monopawly/$code'
      preLoaderRoute: typeof MonopawlyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeowstermindPlayRoute: MeowstermindPlayRoute,
  MonopawlyCodeRoute: MonopawlyCodeRoute,
  MeowstermindIndexRoute: MeowstermindIndexRoute,
  MonopawlyIndexRoute: MonopawlyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
