/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeowstermindIndexRouteImport } from './routes/meowstermind/index'
import { Route as MeowstermindPlayRouteImport } from './routes/meowstermind/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeowstermindIndexRoute = MeowstermindIndexRouteImport.update({
  id: '/meowstermind/',
  path: '/meowstermind/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeowstermindPlayRoute = MeowstermindPlayRouteImport.update({
  id: '/meowstermind/play',
  path: '/meowstermind/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/meowstermind/': typeof MeowstermindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/meowstermind': typeof MeowstermindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meowstermind/play': typeof MeowstermindPlayRoute
  '/meowstermind/': typeof MeowstermindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meowstermind/play' | '/meowstermind/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meowstermind/play' | '/meowstermind'
  id: '__root__' | '/' | '/meowstermind/play' | '/meowstermind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeowstermindPlayRoute: typeof MeowstermindPlayRoute
  MeowstermindIndexRoute: typeof MeowstermindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meowstermind/': {
      id: '/meowstermind/'
      path: '/meowstermind'
      fullPath: '/meowstermind/'
      preLoaderRoute: typeof MeowstermindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meowstermind/play': {
      id: '/meowstermind/play'
      path: '/meowstermind/play'
      fullPath: '/meowstermind/play'
      preLoaderRoute: typeof MeowstermindPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeowstermindPlayRoute: MeowstermindPlayRoute,
  MeowstermindIndexRoute: MeowstermindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
